### ISSUE TITLE
Ok button on iOS prompt doesn't close popup

### ISSUE THREAD

**Issue by mansiva** [zoltangy/react-pwa-install#1]
On iPhone the popup explaining how to install the PWA cannot be closed using the OK button, only by clicking outside of the popup.

![File](https://user-images.githubusercontent.com/1873405/93888980-aa527700-fcb6-11ea-8186-b30d6ac25512.jpg)

**Comment by imdnt** [comment]
Seems like there's no binding to the OK button, might be able to create a pull request soon

**Comment by itsdante** [comment]
@zoltangy would be great if you can approve my PR

**Comment by zoltangy** [comment]
Merged and new version deployed (1.0.12). 
Thank you!
